services:
  db:
    image: postgres:15-alpine
    container_name: biblioteka-db
    environment:
      POSTGRES_DB: biblioteka_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d biblioteka_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./backend
    container_name: biblioteka-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/biblioteka_db?currentSchema=biblioteka
      SPRING_DATASOURCE_USERNAME: app_BookVault
      SPRING_DATASOURCE_PASSWORD: App1dent1ty#Pass!
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  frontend:
    build: ./frontend
    container_name: biblioteka-frontend
    depends_on:
      - app
    ports:
      - "80:80"

volumes:
  postgres_data:
