spring.application.name=library
spring.main.banner-mode=off

# Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteka_db?currentSchema=biblioteka
spring.datasource.username=app_BookVault
spring.datasource.password=App1dent1ty#Pass!

# JPA / Hibernate
spring.jpa.properties.hibernate.default_schema=biblioteka
spring.jpa.hibernate.ddl-auto=validate
# true for more logs
spring.jpa.show-sql=false

# Logging
# for more logs info,debug,debug,
logging.level.root=WARN
logging.level.com.bookvault=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=WARN
logging.level.org.hibernate.orm.results=OFF
logging.level.org.hibernate.orm.results.graph=OFF

jwt.secret=bookvaultsupersecretkeyismustbenoway
jwt.expiration=86400000
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.keepalive-time=60000
