spring.application.name=library

# Po??czenie
spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteka_db?currentSchema=biblioteka
spring.datasource.username=app_BookVault
spring.datasource.password=App1dent1ty#Pass!

# Mapowanie i Walidacja
spring.jpa.properties.hibernate.default_schema=biblioteka
# Na czas pisania mapowa? zostaw 'none', a gdy sko?czysz wszystkie klasy - zmie? na 'validate'
spring.jpa.hibernate.ddl-auto=validate

# Logowanie (?eby? widzia? b??dy mapowania w konsoli)
spring.jpa.show-sql=true
logging.level.org.hibernate.orm.results=DEBUG

jwt.secret=bookvaultsupersecretkeyismustbenoway
jwt.expiration=86400000
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.keepalive-time=60000
